# Generated by Django 4.1.5 on 2023-01-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, max_length=50, null=True)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_from_table', models.CharField(choices=[('people', 'People'), ('enterprise', 'Enterprise'), ('item', 'Item'), ('address', 'Address')], max_length=50)),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('emergency_phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.IntegerField(blank=True, default=0, null=True)),
                ('routing_number', models.IntegerField(blank=True, default=0, null=True)),
                ('bank_card_number', models.IntegerField(blank=True, default=0, null=True)),
                ('bank_card_expiration_date', models.DateField(blank=True, null=True)),
                ('bank_card_secret_code', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('backup_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(default=0, max_length=50)),
                ('amount', models.CharField(max_length=50, null=True)),
                ('unit_price', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('received_date', models.DateField(null=True)),
                ('arrival_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('height', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('shape', models.CharField(max_length=50, null=True)),
                ('length', models.CharField(max_length=50, null=True)),
                ('width', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('received_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('family_name', models.CharField(blank=True, max_length=50, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.ImageField(blank=True, null=True, unique=True, upload_to='')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('to_table', models.CharField(choices=[('people', 'People'), ('enterprise', 'Enterprise'), ('item', 'Item'), ('address', 'Address')], max_length=50)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('addresses_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='idjwi.address')),
                ('contacts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idjwi.contact')),
                ('names_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idjwi.name')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idjwi.name'),
        ),
        migrations.AddField(
            model_name='address',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='idjwi.name'),
        ),
    ]
